[
    {
        "domain": ".netflix.com",
        "expirationDate": 1768615800.804806,
        "hostOnly": false,
        "httpOnly": false,
        "name": "netflix-sans-normal-3-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792375799.654577,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SecureNetflixId",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v%3D3%26mac%3DAQEAEQABABT117n_MnufEHVbp6cXZr2jpwXn6-dSk7I.%26dt%3D1760839798704"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1760841602.276128,
        "hostOnly": false,
        "httpOnly": false,
        "name": "profilesNewSession",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "0"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1760923262.304175,
        "hostOnly": false,
        "httpOnly": true,
        "name": "gsid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "c8eeb693-1cf8-4e47-b834-4336a9b0c7c9"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792375799.654706,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NetflixId",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v%3D3%26ct%3DBgjHlOvcAxKCA85PgCRQ8EMymmqhmnJ2jBD04xiRnAm7nViSu9gxeys-mQKaBwa_0cU-dl8jaPsF8yER3ZSrrjR3SXRsG-_Ve_kSaJaPDIG6CW04ppmTE3nbne8d8k1MxufyFe37ttLybx9J3Lb9hRhvsKtPfKgWyF0u507KzchqJJJhpjJNp8mnSjC-onq4jZaeT3sOVR1GvGW7PdzCZ61a45Z2tmli098IzvrW0PrlDSkKTXE5yuaruGUAtc9JmncnxQyaa9_ENzm9Z4ijCM7oyxJFQ0MtCI8nxJm6pjR5GJ4vqVXX6Ft2qFba4OIWywEBRTEuyRNbHzr8WL_F0I88OMDCjAYtGdbjpcs5sMkga8cvseEwEZ5BCqtEm4xZ_mU3g4uEhey4jww56aiaKtqs5ao5UlJOa0qSuCUqUVz9QKcPke5PI_CRjYkkKb1a4SMcW2p1oXS0UilRje1qb73lF9ZCAMonE1r5afXrrp4d3zCMREX3Dfi2tE1AVsxUJVNy3V_Gq9YrQYznGAYiDgoMGIngYpWgHnrlUfEw%26pg%3DZJJW25PRMJBTVCQAOM4BINMNNE%26ch%3DAQEAEAABABTW6S9WVi7wk-xg9P1tSjnSE4BWG5DCjIQ."
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1768615800.804643,
        "hostOnly": false,
        "httpOnly": false,
        "name": "pas",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "%7B%22supplementals%22%3A%7B%22muted%22%3Atrue%7D%7D"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792375800,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonConsent",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "isGpcEnabled=0&datestamp=Sun+Oct+19+2025+09%3A10%3A00+GMT%2B0700+(Indochina+Time)&version=202508.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=adfaab0a-6dee-4c66-832e-c8e64db4029e&interactionCount=1&isAnonUser=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1&AwaitingReconsent=false"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1795399795.159598,
        "hostOnly": false,
        "httpOnly": true,
        "name": "dsca",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1760850574.183264,
        "hostOnly": false,
        "httpOnly": false,
        "name": "flwssn",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "aeb81b2b-4772-440d-b04d-3c8833eb69bb"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1768615800.804885,
        "hostOnly": false,
        "httpOnly": false,
        "name": "netflix-sans-bold-3-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792375794.275674,
        "hostOnly": false,
        "httpOnly": false,
        "name": "nfvdid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "BQFmAAEBEL2ohOGU5a3kSTavSwE5J9BgyA4mwua5CPXuz496OgaAvb3qS5RskawwRd1yekDQ2yWgKeRzbyKoMdoThwJeMSuffVFR4s5KxpSocOH37POLvZ9-JyNO7Rr7iNRyZFw-jPHyg3RwanShUUxu4yWGNh-t"
    }
]
