[
    {
        "domain": ".netflix.com",
        "expirationDate": 1768726713.595165,
        "hostOnly": false,
        "httpOnly": false,
        "name": "netflix-sans-normal-3-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792460777.595927,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SecureNetflixId",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v%3D3%26mac%3DAQEAEQABABT4-cBELvmo_hpawd_p9PmzTndGRycu640.%26dt%3D1760924776476"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1760952518.679468,
        "hostOnly": false,
        "httpOnly": false,
        "name": "profilesNewSession",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "0"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1761011178.10136,
        "hostOnly": false,
        "httpOnly": true,
        "name": "gsid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "a4bf2939-716f-4034-86e9-4548e6f7e834"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792460777.59599,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NetflixId",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "ct%3DBgjHlOvcAxKcA2TS2zWE5rz-TKhBEjjuPMK9PvUyZNZLRS2iOUify61iP6DJgysCd6MneKPKctRxNggs62PeFJ57ha3a5yoQ6LmoLp4Z1-14fPnAU4w0HLB6ubo6ISto-BT34X8joLN0IWOfuaOy9Z9QVdl3rRKrWSVAgsOJhOSdQTMEhdviuUNnxp8Yssam4pisb8daf8qQ6J94lhfBV3Ui83y92R5H5f3AunJ8byT0Ytc6eaO1CP-Py3dv1rnMIUR3qpCGB_ynvOYqIo8U2WRuxMDAqpokngi9R310Zg3n-fQxtWxYbfKpgcQK3wYHZ0VUBjAj9niETC5R4H1ep3WWXix25MqeU_k0V-NxsRcrbeyIZuOvtqt7ynJ-c4OtJJabR_zwSlFxOoqfGqRtl_GHQ4EkSjuW1baNMNzyMkqoF74LGBRiEFuYCMCLqnndrPzkpmk6iyj4hlhbcPcefB3l10z-0fpva7Cas4o9SYI_mk8pn4_FNG5F9Vu1_zilTGywk4jcrNppge-yhpg9VoDwjZWEp3TBzBAuVOwOEkijrIPFNhMYBiIOCgydpTrPijvIabkMnr8.%26ch%3DAQEAEAABABTW6S9WVi7wk-xg9P1tSjnSE4BWG5DCjIQ.%26v%3D3%26pg%3DZJJW25PRMJBTVCQAOM4BINMNNE"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1768726713.59504,
        "hostOnly": false,
        "httpOnly": false,
        "name": "pas",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "%7B%22supplementals%22%3A%7B%22muted%22%3Atrue%7D%7D"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792486715,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonConsent",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "isGpcEnabled=0&datestamp=Mon+Oct+20+2025+15%3A58%3A35+GMT%2B0700+(Indochina+Time)&version=202508.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=adfaab0a-6dee-4c66-832e-c8e64db4029e&interactionCount=1&isAnonUser=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1&AwaitingReconsent=false"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1795399795.159598,
        "hostOnly": false,
        "httpOnly": true,
        "name": "dsca",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1760961513.147208,
        "hostOnly": false,
        "httpOnly": false,
        "name": "flwssn",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "904b093c-8b56-4ffb-822e-09a46a420c5d"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1768726713.595227,
        "hostOnly": false,
        "httpOnly": false,
        "name": "netflix-sans-bold-3-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792375794.275674,
        "hostOnly": false,
        "httpOnly": false,
        "name": "nfvdid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "BQFmAAEBEL2ohOGU5a3kSTavSwE5J9BgyA4mwua5CPXuz496OgaAvb3qS5RskawwRd1yekDQ2yWgKeRzbyKoMdoThwJeMSuffVFR4s5KxpSocOH37POLvZ9-JyNO7Rr7iNRyZFw-jPHyg3RwanShUUxu4yWGNh-t"
    }
]
