[
    {
        "domain": ".netflix.com",
        "expirationDate": 1768657447.164694,
        "hostOnly": false,
        "httpOnly": false,
        "name": "netflix-sans-normal-3-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792380825.98969,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SecureNetflixId",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v%3D3%26mac%3DAQEAEQABABSAAAJLAi_2_UycKmgbOQ-T4rjdCB_z1Hc.%26dt%3D1760844824956"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1760923262.304175,
        "hostOnly": false,
        "httpOnly": true,
        "name": "gsid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "c8eeb693-1cf8-4e47-b834-4336a9b0c7c9"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792380825.989812,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NetflixId",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v%3D3%26ct%3DBgjHlOvcAxKCA-HGzp2V6w5EAzqqx2SPL2NuT62IyBwD8weQ4QthTZALfVwPk8zdnUgDsg5T2tSh99W2ea_SRvL3gObQTxSjzbYenBdhOAhJVmB1U2GZ8bjWq_uUlDViWLOIUBKEe-9eRPGelwPr5-zpqtioaJpFVuf0Nl5J_PmE4P_huMeG_dFUtJ6DDfczkEUevXbx09afA-8C9rrGp_zlTPXh-pZ0MlZu30edE4J5o7ENL9z1CPyoTaNzqSIi3j3_4bf_q-itDB1NGWiY0T9uONHIJSLasq9RLHOd58MgqNbmwKINqd7fIujHpFrhT9LP3dF-HVArg-FaCofN42UWjO5oKbeTFTOLkY5bdpeOcuI-1s5YC6ZuPptxoUskWNCt_dapNAn4b-9Z2QO9Ko2QT6D1sDdUNxCh7QR60M5GTJqjHAUs-TdL7gJC86RTWPbdkE0-he9aMqLEjUxgsgQSk7AZ87Omwr3kXkA6kT18ySu0D3_DcmRh9kWHUbe1QY4s1eTH1C4oslE6GAYiDgoMnplpkjS9RndvLjdJ%26pg%3DZJJW25PRMJBTVCQAOM4BINMNNE%26ch%3DAQEAEAABABTW6S9WVi7wk-xg9P1tSjnSE4BWG5DCjIQ."
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1768657447.164524,
        "hostOnly": false,
        "httpOnly": false,
        "name": "pas",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "%7B%22supplementals%22%3A%7B%22muted%22%3Atrue%7D%7D"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792417449,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonConsent",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "isGpcEnabled=0&datestamp=Sun+Oct+19+2025+20%3A44%3A09+GMT%2B0700+(Indochina+Time)&version=202508.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=adfaab0a-6dee-4c66-832e-c8e64db4029e&interactionCount=1&isAnonUser=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1&AwaitingReconsent=false"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1795399795.159598,
        "hostOnly": false,
        "httpOnly": true,
        "name": "dsca",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1760892246.650572,
        "hostOnly": false,
        "httpOnly": false,
        "name": "flwssn",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "2c2d64c2-2a6f-464e-9cb7-4d6d5f08a432"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1768657447.164762,
        "hostOnly": false,
        "httpOnly": false,
        "name": "netflix-sans-bold-3-loaded",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".netflix.com",
        "expirationDate": 1792375794.275674,
        "hostOnly": false,
        "httpOnly": false,
        "name": "nfvdid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "BQFmAAEBEL2ohOGU5a3kSTavSwE5J9BgyA4mwua5CPXuz496OgaAvb3qS5RskawwRd1yekDQ2yWgKeRzbyKoMdoThwJeMSuffVFR4s5KxpSocOH37POLvZ9-JyNO7Rr7iNRyZFw-jPHyg3RwanShUUxu4yWGNh-t"
    }
]
